@baseUrl = http://localhost:3000

# Recados
###
GET {{baseUrl}}/recados/
###

GET {{baseUrl}}/recados/332
###

# Post de recados
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "name": "Recado 1",
    "text": "Texto do recado 1"
}
###